; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env]
build_flags = 
    -D CONFIG_USE_SERIAL_DEBUG=true
    -D CONFIG_DEBUG_PORT=Serial

	; enable/disable CLI
    -D CONFIG_CLI_ENABLED=true

	; I2C
	-D CONFIG_I2C_PORT=0
	-D CONFIG_I2C_SDA_PIN=23
	-D CONFIG_I2C_SCL_PIN=22

	; SDCard
	-D CONFIG_SDCARD_SPI_PORT=1
	-D CONFIG_SDCARD_CS_PIN=21
	-D CONFIG_SDCARD_CMD_PIN=18
	-D CONFIG_SDCARD_CLK_PIN=5
	-D CONFIG_SDCARD_DATA0_PIN=19

	; Cellular
	-D CONFIG_CELL_UART_PORT=Serial1
	-D CONFIG_CELL_UART_BAUDRATE=115200
	-D CONFIG_CELL_UART_TX_PIN=16
	-D CONFIG_CELL_UART_RX_PIN=17
	-D CONFIG_CELL_UART_RTS_PIN=27
	-D CONFIG_CELL_UART_CTS_PIN=33
	-D CONFIG_CELL_INT_PWR_EN_PIN=13
	-D CONFIG_CELL_RI_PIN=12
	-D CONFIG_CELL_DTR_PIN=14
	-D CONFIG_CELL_POWER_KEY_PIN=32

	-D BOARD_HAS_PSRAM
	-D CORE_DEBUG_LEVEL=1
	-mfix-esp32-psram-cache-issue
    
    ; Device Info
    -D CONFIG_DEVICE_NAME=\"Terraair\"
	-D CONFIG_FW_VERSION=\"2.0.0-1\"
    -D CONFIG_HW_VERSION=\"1\"
	-D CONFIG_FW_RELEASE_DATETIME=251026

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
board_build.mcu = esp32
board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_size = 8MB
board_build.flash_mode = dio ; for N8R2 board
board_build.arduino.memory_type = dio_qspi
board_build.partitions = partitions.csv

upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
upload_speed = 921600
monitor_filters = direct
build_flags = 
	${env.build_flags}
extra_scripts = pre:extra_script.py
lib_deps = 
	vshymanskyy/TinyGSM@^0.12.0
	knolleary/PubSubClient@^2.8